apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - ../../base
images:
  - name: ghcr.io/anhquantrl/shipping
    newName: ghcr.io/anhquantrl/shipping
    newTag: main
