apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - ../../base
patches:
  - path: deploy.yaml
images:
  - name: ghcr.io/anhquantrl/ad
    newName: ghcr.io/anhquantrl/ad
    newTag: main
