apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-registry
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: ".dockerconfigjson"
      remoteRef:
        key: data/ghcr
        property: AUTH
