apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
- ../../base
images:
- digest: sha256:0c6e30fa42c7653e53b0ecd07c27e16d0628a1bd457b82db0adfea076cbcd279
  name: ghcr.io/anhquantrl/frontend
  newName: ghcr.io/anhquantrl/frontend
  newTag: main
