apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
- ../../base
images:
- digest: sha256:2e77ea1a7f5799650cf8a498bf2a38c86dbcd991df487144ff9b9944b1108ca5
  name: ghcr.io/anhquantrl/productcatalog
  newName: ghcr.io/anhquantrl/productcatalog
  newTag: main
